SCRIPT_HEADER = '''from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import (
    col, lit, when, coalesce, current_date, current_timestamp,
    to_date, date_format, date_trunc, months_between, add_months,
    substring, instr, lpad, rpad, concat_ws, collect_list,
    row_number, rank, dense_rank, sum, count, avg, max, min,
    cast, regexp_replace, trim, upper, lower, length
)
from pyspark.sql.window import Window
from pyspark.sql.types import (
    StructType, StructField, StringType, LongType, DoubleType,
    DecimalType, TimestampType, BooleanType, IntegerType, FloatType
)

# Initialize SparkSession
spark = SparkSession.builder \\
    .appName("OracleToSparkMigration") \\
    .getOrCreate()

# Set log level
spark.sparkContext.setLogLevel("WARN")
'''

DATABRICKS_HEADER = '''# Databricks notebook source
# COMMAND ----------
# Oracle to PySpark Conversion - Databricks Notebook
# Generated by Oracle→PySpark Converter

from pyspark.sql import functions as F
from pyspark.sql.functions import (
    col, lit, when, coalesce, current_date, current_timestamp,
    to_date, date_format, months_between, add_months,
    substring, instr, lpad, rpad, concat_ws, collect_list,
    row_number, rank, dense_rank
)
from pyspark.sql.window import Window
from pyspark.sql.types import *

# Note: SparkSession is pre-configured in Databricks
# spark = SparkSession.builder.getOrCreate()  # Uncomment if needed outside Databricks
'''

COMMON_IMPORTS = '''from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import col, lit, when, coalesce
from pyspark.sql.window import Window
'''
